import { forwardRef } from 'react'
import { ACTION_STATUS_BY_KEY, bodyPartLabel } from '../lib/constants'

const fmt = (v) => (v == null || v === '' ? '—' : v)
const personLine = (p) =>
  p.kind === 'internal'
    ? `${p.name || 'Unnamed'}${p.dept ? ` (${p.dept})` : ''} · Internal`
    : `${p.name || 'Unnamed'}${p.company ? `, ${p.company}` : ''}${p.contact ? ` · ${p.contact}` : ''} · External`

function Section({ title, children }) {
  return (
    <section className="print-block mb-5">
      <h2 className="mb-2 border-b-2 border-ink-900 pb-1 text-sm font-extrabold uppercase tracking-wide text-ink-900">{title}</h2>
      {children}
    </section>
  )
}
function Field({ label, value }) {
  return <div className="mb-1.5"><span className="text-[11px] font-bold uppercase tracking-wide text-ink-500">{label}: </span><span className="text-sm text-ink-900">{fmt(value)}</span></div>
}

/** Printable occupational-illness report. */
const IllnessReportDoc = forwardRef(function IllnessReportDoc({ illness, org }, ref) {
  if (!illness) return <div ref={ref} />
  return (
    <div ref={ref} className="mx-auto max-w-[800px] bg-white p-8 text-ink-900">
      <div className="mb-6 flex items-start justify-between border-b-4 border-brand-600 pb-4">
        <div>
          <h1 className="text-2xl font-black text-brand-700">Occupational Illness Report</h1>
          <p className="text-sm text-ink-500">{org?.name || 'Organization'}</p>
        </div>
        <div className="text-right">
          <p className="text-lg font-extrabold">{illness.refNo}</p>
          <p className="text-xs text-ink-500">Generated {new Date().toLocaleDateString()}</p>
        </div>
      </div>

      <Section title="Exposure Details">
        <div className="grid grid-cols-2 gap-x-8">
          <Field label="Date" value={illness.date} />
          <Field label="Time" value={illness.time} />
          <Field label="Location" value={illness.location} />
          <Field label="Site" value={illness.site} />
          <Field label="Exposed to agent" value={illness.exposedToAgent} />
          <Field label="Duration of exposure" value={illness.exposureDuration} />
          <Field label="PPE in use" value={(illness.ppe || []).join(', ')} />
        </div>
      </Section>

      <Section title="Affected People">
        {(illness.affectedPersonnel || []).length === 0 ? <p className="text-sm text-ink-400">None recorded.</p> : (
          <ul className="list-disc pl-5 text-sm">{illness.affectedPersonnel.map((p) => <li key={p.id}>{personLine(p)}</li>)}</ul>
        )}
      </Section>

      <Section title="Health Issue Triggered">
        <p className="whitespace-pre-wrap text-sm leading-relaxed">{fmt(illness.healthIssue)}</p>
      </Section>

      <Section title="Affected Body Parts">
        <p className="text-sm">{(illness.affectedBodyParts || []).map(bodyPartLabel).join(', ') || '—'}</p>
      </Section>

      <Section title="Corrective Actions">
        {(illness.actions || []).length === 0 ? <p className="text-sm text-ink-400">No actions recorded.</p> : (
          <table className="w-full border-collapse text-sm">
            <thead><tr className="border-b border-ink-300 text-left text-[11px] uppercase text-ink-500"><th className="py-1 pr-2">Action</th><th className="py-1 pr-2">Owner</th><th className="py-1 pr-2">Due</th><th className="py-1">Status</th></tr></thead>
            <tbody>
              {illness.actions.map((a) => (
                <tr key={a.id} className="border-b border-ink-100 align-top">
                  <td className="py-1 pr-2">{a.description}</td><td className="py-1 pr-2">{a.ownerName}</td><td className="py-1 pr-2">{a.dueDate}</td><td className="py-1">{ACTION_STATUS_BY_KEY[a.status]?.label || a.status}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Section>

      <p className="mt-8 border-t border-ink-200 pt-3 text-[10px] text-ink-400">
        Generated by Incident IRA. A record-keeping aid; it does not replace any statutory occupational-health reporting obligation.
      </p>
    </div>
  )
})

export default IllnessReportDoc
